# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install packages
      run: sudo apt install -y curl screen
    - name: Install Node
      run: |
        curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
        sudo apt install -y nodejs
    # Runs a set of commands using the runners shell
    - name: Install homebridge
      run: sudo npm install --unsafe-perm -g homebridge
    
    - name: npm install and build
      run: |
        cd $GITHUB_WORKSPACE
        npm install
        npm run build
    - name: Copying test config to right place
      run: |
        mkdir ~/.homebridge
        cp $GITHUB_WORKSPACE/test/config.json ~/.homebridge/config.json
        sudo cp -R $GITHUB_WORKSPACE /usr/lib/node_modules/
        chmod +x $GITHUB_WORKSPACE/test/test.sh
    # Run homebridge in screen
    - name: Running homebridge
      run: $GITHUB_WORKSPACE/test/test.sh
